fragment GlobalParts on Global {
  __typename
  header {
    __typename
    logo
    navLinks {
      __typename
      label
      href
    }
  }
  footer {
    __typename
    logo
    copyright
    socialLinks {
      __typename
      platform
      url
    }
    funding {
      __typename
      text
      logo
    }
  }
}

fragment HomeParts on Home {
  __typename
  title
  hero {
    __typename
    heading
    subheading
    images
  }
  technology {
    __typename
    heading
    subheading
    description
    image
    gallery
    features {
      __typename
      title
      icon
      description
      detailedDescription
    }
  }
  application {
    __typename
    heading
    subheading
    description
    features {
      __typename
      title
      image
      description
      detailedDescription
    }
  }
  pilots {
    __typename
    heading
    subheading
    description
    sites {
      __typename
      name
      image
      description
      crop
      status
    }
  }
  partners {
    __typename
    heading
    subheading
    description
    partners {
      __typename
      name
      logo
    }
  }
  body
}

fragment BlogParts on Blog {
  __typename
  title
  excerpt
  image
  category
  date
  readTime
  author
  authorRole
  featured
  body
}

fragment MediaParts on Media {
  __typename
  title
  type
  image
  videoUrl
  category
  description
  date
}

fragment PublicationsParts on Publications {
  __typename
  title
  journal
  year
  fileSize
  downloads
  category
  color
  pdfUrl
  body
}
